spring.application.name=lumiora-backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/lumiora
spring.datasource.username=root
spring.datasource.password=Chandra30071

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.open-in-view=false


# Lumiora Bootstrap Admin
lumiora.bootstrap.admin.email=admin@lumiora.com
lumiora.bootstrap.admin.password=ChangeMe123!
lumiora.bootstrap.admin.first-name=Super
lumiora.bootstrap.admin.last-name=Admin
lumiora.bootstrap.admin.phone=9999999999